collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4802867
color:
  saturation: 0.7706093
  brandStrength: 0.390681
  lightness: 0.2401434
  brandColors:
    - '#282E30'
    - '#EFE1B4'
    - '#C6A34B'
    - '#6E5B42'
    - '#F3EFE6'
  rhythmicContrast: 0.7473118
layout_spectrum: 0.4820789
name: EllisReed
