favicon: null
name: Ellis Reed
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7706093
  brandStrength: 0.5215054
  lightness: 0.6594982
  brandColors:
    - '#252722'
    - '#B3C8DB'
    - '#5C9BC6'
    - '#5D5958'
    - '#B37A42'
  rhythmicContrast: 0.4569893
typography_spectrum: 0.1415771
layout_spectrum: 0.50885
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
